export enum ErrorCode {
  REQUIRED = 'REQUIRED',
  NOT_NULL = 'NOT_NULL',
  NOT_EMPTY = 'NOT_EMPTY',
  INVALID_TYPE = 'INVALID_TYPE',
  MIN_VALUE = 'MIN_VALUE',
  MAX_VALUE = 'MAX_VALUE',
  RANGE = 'RANGE',
  MIN_LENGTH = 'MIN_LENGTH',
  MAX_LENGTH = 'MAX_LENGTH',
  LENGTH_RANGE = 'LENGTH_RANGE',
  INVALID_FORMAT = 'INVALID_FORMAT',
  PATTERN_MISMATCH = 'PATTERN_MISMATCH',
  CONTAINS_FORBIDDEN = 'CONTAINS_FORBIDDEN',
  MISSING_REQUIRED = 'MISSING_REQUIRED',
  CROSS_FIELD_INVALID = 'CROSS_FIELD_INVALID',
  CUSTOM_ERROR = 'CUSTOM_ERROR',
  ASYNC_VALIDATION_FAILED = 'ASYNC_VALIDATION_FAILED',
  SECURITY_RISK = 'SECURITY_RISK',
  CONTENT_POLICY = 'CONTENT_POLICY',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PHONE = 'INVALID_PHONE',
  INVALID_URL = 'INVALID_URL',
  INVALID_UUID = 'INVALID_UUID',
  INVALID_IP = 'INVALID_IP',
  INVALID_DATE = 'INVALID_DATE',
  PAST_DATE = 'PAST_DATE',
  FUTURE_DATE = 'FUTURE_DATE',
}

export type Severity = 'error' | 'warning' | 'info';

export interface ValidationError {
  field: string;
  errorCode: ErrorCode | string;
  message: string;
  severity: Severity;
  params?: Record<string, any>;
}
